title: Aerin Parker
description: > # this means to ignore newlines until "baseurl:"
  A blog to update progress on MARS.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Aerin Parker # add your name
author-img: david-freeman.jpg # add your photo
about-author: # add description
social-twitter: AerinParker # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: AerinParker # add your Github handle
social-linkedin: Aerin Parker # add your Linkedin handle
social-email: parkerak2@g.cofc.edu # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
